# Site settings
title:          Cloud Native Life
description:    "organized journals of my cognitive universe."
domain:         "berylleta.dev"
baseurl:        ""
url:            "https://berylleta.dev"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Beryl Leta
  url:          https://berylleta.dev
  email:        contact@berylleta.dev

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

theme:      tale

# permalinks
permalink:  /:year-:month-:day/:title
paginate:   5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus: berylleta